# Generated by Django 5.0.4 on 2024-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name": "Tax", "verbose_name_plural": "Taxes"},
        ),
    ]
