# Generated by Django 5.0.4 on 2024-05-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="images",
            new_name="image",
        ),
    ]
