# Generated by Django 5.0.4 on 2024-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_rename_images_fooditem_image"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("vendor", "name")},
        ),
    ]
