# Generated by Django 5.0.4 on 2024-05-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_category_name_alter_category_unique_together"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fooditem",
            unique_together={("food_title", "category", "vendor")},
        ),
    ]
