# Generated by Django 5.0.4 on 2024-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_fooditem_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
